apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-db
  namespace: x-com
spec:
  selector:
    matchLabels:
      app: auth-service-db
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          envFrom:
            - secretRef:
                name: auth-secret
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: auth-service-db-pvc

