apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: x-com
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: bitnami/minio:latest
          args:
            - server
            - /data
            - "--console-address"
            - ":9001"
          envFrom:
            - secretRef:
                name: minio-secret
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: minio-pvc
