apiVersion: v1
kind: Secret
metadata:
  name: post-secret
  namespace: x-com
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "konevtsov"
  POSTGRES_DB: "x-post-service"
  POSTGRES_HOST: "post-service-db"
  POSTGRES_PORT: "5432"

  AUTH_API_BASE_URL: "http://x-auth-svc:8001/api/v1"
  
  S3_ENDPOINT_URL: "http://minio:9000"
  S3_ACCESS_KEY: "PSYm/SHU5dz6gWBHRa4zGg=="
  S3_SECRET_KEY: "a3d/SiBP2cdY5CACEok9Ig=="