apiVersion: v1
kind: Secret
metadata:
  name: post-secret
  namespace: x-com
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "konevtsov"
  POSTGRES_DB: "x-post-service"
  POSTGRES_HOST: "post-service-db"
  POSTGRES_PORT: "5432"