apiVersion: v1
kind: Service
metadata:
  name: x-post-svc
  namespace: x-com
spec:
  selector:
    app: x-post-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: post-svc
  type: ClusterIP
