apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: x-com
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "konevtsov"
  POSTGRES_DB: "x-auth-service"
  POSTGRES_HOST: "auth-service-db"
  POSTGRES_PORT: "5432"