apiVersion: v1
kind: Service
metadata:
  name: x-auth-svc
  namespace: x-com
spec:
  selector:
    app: x-auth-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: auth-svc
  type: ClusterIP
