services:
  postgres:
    image: postgres:17-alpine
    hostname: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - src/.env
    networks:
      - auth-service-network

  app:
    build: .
    container_name: auth-service
    restart: always
    depends_on:
      - postgres
    ports:
      - 8001:8001
    networks:
      - auth-service-network

networks:
  auth-service-network:
    driver: bridge

volumes:
  postgres-data:
