apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: x-auth-service
  labels:
    app: auth-service
  spec:
    replicas: {{ .Values.replicas }}
    selector:
      matchLabels:
        app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "nerdcode/x-auth-service: {{ .Values.version }}"
          env:
            - name: PORT
              value: "8001"
          envFrom:
            - secretRef:
                name: auth-service-db-url
          ports:
            - containerPort: 8001
              protocol: TCP