apiVersion: v1
kind: Service
metadata:
  name: x-user-svc
  namespace: x-com
spec:
  selector:
    app: x-user-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: user-svc
  type: ClusterIP
