apiVersion: v1
kind: Secret
metadata:
  name: user-secret
  namespace: x-com
type: Opaque
stringData:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "konevtsov"
  POSTGRES_DB: "x-user-service"
  POSTGRES_HOST: "user-service-db"
  POSTGRES_PORT: "5432"