name: lint
on:
  push:
    paths:
      - 'x-auth-service/**'
    pull_requests:
      paths:
        - 'x-auth-service/**'
jobs:
    lint:
        name: "Run linters"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13.1"
            - name: Install poetry
              run: |
                python -m pip install --upgrade pip poetry==1.8.3 
                poetry config virtualenvs.create false --local
            - name: Install dependencies
              run: |
                  run: poetry install --all-extras

            - name: Run ruff for tests
              uses: astral-sh/ruff-action@v1
              with:
                  src: "./tests"

            - name: Ruff for src
              run: ruff check --fix

            - name: Format
              run: ruff format