name: x-post-service-testing
on:
  push:
    paths:
      - 'x-post-service/**'
  pull_request:
    paths:
      - 'x-post-service/**'

defaults:
  run:
    working-directory: x-post-service

jobs:
    lint:
        name: "Run linters"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.12.3"
            - name: Install poetry
              run: |
                python -m pip install --upgrade pip poetry==1.8.3 
                poetry config virtualenvs.create false --local
            - name: Install dependencies
              run: |
                  poetry install --all-extras

            - name: Ruff check
              run: ruff check --fix

            - name: Ruff Format
              run: ruff format
